name: Go tests
on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Fetch dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
